# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: p2p-mesh-network
email: tom.vaneyck@telenet.be
description: >- # this means to ignore newlines until "baseurl:"
  
baseurl: "/p2p-mesh-network" # the subpath of your site, e.g. /blog
url: "https://tomvaneyck.github.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  tomvaneyck

# Build settings
source: contents
search: true
search_tokenizer_separator: /[\s/]+/
aux_links:
  "Repository":
    - //github.com/tomvaneyck/p2p-mesh-network
  "Npm package":
    - "//npmjs.com/tomvaneyck/p2p-mesh-network"
heading_anchors: true
footer_content: "Copyright &copy; 2019 Tom Van Eyck. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"
color_scheme: nil
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Default github pages config
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge